name: Build SPA and Docker Image (CI)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci
        working-directory: ./spa
      # - run: npm install
      
      - run: npm run build --if-present
        working-directory: ./spa
      
      # - run: npm test
      #   working-directory: ./spa
      
      - run: mkdir -p ./src/spa
      - run: cp -R ./spa/dist/* ./src/spa/
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/alirionx/csp-lineitem-collector:latest